name: daily-monitor

on:
  schedule:
    - cron: '0 6 * * 1'   # 매주 월요일 KST 15:00 (UTC 06:00)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
      - name: Run monitor (GPT OFF)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          ENABLE_GPT: "0"    # GPT 끔
        run: |
          python run_all_and_notify.py
